name: Validate Bicep Scripts Backend Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "**"
    # paths:
    #   - 'backend-integration/**'
    #   - '.github/workflows/lib-azure-bicep-validation.yml'
      
# Use concurrency to ensure that only a single job or workflow using the same concurrency group will run at a time
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true  # Cancel previously queued jobs and run the latest
  
jobs:
  backend-integration-validation: 
    uses: ./.github/workflows/lib-azure_bicep_validation.yml
    with:
      work-dir: backend-integration
    secrets:
      SELF_HOSTED_RUNNER_TOKEN: ${{ secrets.SELF_HOSTED_RUNNER_TOKEN }}