name: Deploy Backend Integration to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend-integration/**'
      - '.github/workflows/backend-integration-azure_deploy.yml'

# Use concurrency to ensure that only a single job or workflow using the same concurrency group will run at a time
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true  # Cancel previously queued jobs and run the latest


jobs:
  backend-integration-dev: 
    uses: ./.github/workflows/lib-azure_deploy.yml
    with:
      work-dir: backend-integration
      environment: ${{ vars.BACKEND_INTEGRATION_ENV_NAME }}
    secrets:
      SELF_HOSTED_RUNNER_TOKEN: ${{ secrets.SELF_HOSTED_RUNNER_TOKEN }}
      AZURE_CLIENT_ID: ${{ vars.BACKEND_INTEGRATION_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.BACKEND_INTEGRATION_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.BACKEND_INTEGRATION_SUBSCRIPTION_ID }}
      AZURE_LOCATION: ${{ vars.BACKEND_INTEGRATION_LOCATION }}