name: Backend Integration - Checks & documentation

on:
  pull_request:
    paths:
        - 'backend-integration/**'
        - '.github/workflows/backend-integration-dev-code_validation_and_docs.yml'

# Use concurrency to ensure that only a single job or workflow using the same concurrency group will run at a time
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true  # Cancel previously queued jobs and run the latest

jobs:
  backend-integration:
    uses: ./.github/workflows/lib-backend_code_validation_and_docs.yml
    with:
        app-name: backend-integration
        environment: dev
        work-dir: backend-integration
        repo-name: azure-function-app-boilerplate
    secrets:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}