name: Validate bicep scripts
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend-integration/**'
      
# Use concurrency to ensure that only a single job or workflow using the same concurrency group will run at a time
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true  # Cancel previously queued jobs and run the latest
  

jobs:
    build:
      timeout-minutes: 10
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Azure CLI script
          uses: azure/CLI@v2.1.0
          with:
            inlineScript: az config set bicep.use_binary_from_path=false && az bicep build -f backend-integration/infra/main.bicep

        - name: Log in with Azure (Federated Credentials)
          if: ${{ env.AZURE_CLIENT_ID != '' }}
          run: |
            azd auth login \
              --client-id "$AZURE_CLIENT_ID" \
              --federated-credential-provider "github" \
              --tenant-id "$AZURE_TENANT_ID"
