name: Validate Bicep Scripts

on:
  workflow_call:
    inputs:
      work-dir:
        required: true
        type: string 

    secrets:
      SELF_HOSTED_RUNNER_TOKEN: 
        required: true   

jobs:
    self-hosted-status:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      outputs:
        runner-status: ${{ steps.runnerstatus.outputs.status }}
      steps:
        - name: Check runner status
          id: runnerstatus
          uses: SatelCreative/satel-gh-runner-check@1.0.3
          with:       
            github-runner-token: ${{ secrets.SELF_HOSTED_RUNNER_TOKEN }} #Should have access to manage runner
            org-name: SatelCreative

    validate-bicep:
      timeout-minutes: 10
      needs: [self-hosted-status]
      runs-on: ${{ contains(needs.self-hosted-status.outputs.runner-status, 'online') && 'self-hosted' || 'ubuntu-latest' }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4

            # Install Azure CLI only on GitHub-hosted runners
        - name: Install Azure CLI (GitHub-hosted only)
          if: ${{ runner.os == 'Linux' && startsWith(runner.name, 'GitHub Actions') }}
          run: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

        - name: Validate Bicep
          run: |
            az config set bicep.use_binary_from_path=false
            az bicep build -f ${{ inputs.work-dir }}/infra/main.bicep
