name: Validate Bicep Scripts

on:
  workflow_call:
    inputs:
      work-dir:
        required: true
        type: string 

    secrets:
      SELF_HOSTED_RUNNER_TOKEN: 
        required: true   

jobs:
    self-hosted-status:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      outputs:
        runner-status: ${{ steps.runnerstatus.outputs.status }}
      steps:
        - name: Check runner status
          id: runnerstatus
          uses: SatelCreative/satel-gh-runner-check@1.0.3
          with:       
            github-runner-token: ${{ secrets.SELF_HOSTED_RUNNER_TOKEN }} #Should have access to manage runner
            org-name: SatelCreative

    validate-bicep:
      timeout-minutes: 10
      needs: [self-hosted-status]
      runs-on: ${{ contains(needs.self-hosted-status.outputs.runner-status, 'online') && 'self-hosted' || 'ubuntu-latest' }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Azure CLI
          uses: azure/setup-cli@v3

        - name: Validate Bicep
          run: |
            az config set bicep.use_binary_from_path=false
            az bicep build -f ${{ inputs.work-dir }}/infra/main.bicep

        - name: Log in with Azure (Federated Credentials)
          if: ${{ env.AZURE_CLIENT_ID != '' }}
          run: |
            azd auth login \
              --client-id "$AZURE_CLIENT_ID" \
              --federated-credential-provider "github" \
              --tenant-id "$AZURE_TENANT_ID"
